apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: fluentd
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "elk-es-http"
            - name: FLUENT_ELASTICSEARCH_PASSWORD
              value: ""
              valueFrom:
                secretKeyRef:
                  name: fluentd-config
                  key: elasticsearch-password
            - name: FLUENT_ELASTICSEARCH_USER
              value: ""
              valueFrom:
                secretKeyRef:
                  name: fluentd-config
                  key: elasticsearch-user
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: "http"
