apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: fluentd-config

labels:
  - pairs:
      app: fluentd
      managedBy: argocd
      managementCodeGroup: chrismlee42
      managementCodeProject: fluentd-config

namespace: kube-system

patchesStrategicMerge:
  - fluentd-daemonset-patch.yaml

resources:
  # Fluentd daemonset for Elasticsearch https://github.com/fluent/fluentd-kubernetes-daemonset/releases
  - https://raw.githubusercontent.com/fluent/fluentd-kubernetes-daemonset/refs/tags/v1.19.0-1.1/fluentd-daemonset-elasticsearch.yaml
  - fluentd-config-secret.yaml
